CC = g++
CXX = g++
hello:hello.cpp
boyer_moore:boyer_moore.cpp
rabin_karp:rabin_karp.cpp
string:string.cpp	
all: hello boyer_moore rabin_karp string

clean:
	rm -rf {hello,boyer_moore,rabin_karp,string}
